#!/usr/bin/env python3
"""gen_faction_matrix.py — generates docs/factions/MATRIX.md (MASTER_REPORT §5.1).

For every faction defined in the live World rules: internal ID, display name,
side, source, selectable / Random-pool / Tournament-pool status, owning rule
location, roster counts, AI wiring status, and Fluent tooltip coverage.
"""

from __future__ import annotations

import re
import sys
from collections import Counter

from audit_fluent import looks_like_fluent
from cameo_model import Model
from miniyaml import load as load_yaml
from report import table

GAME_OF_SIDE_HINTS = {
    "td_gdi": "C&C Tiberian Dawn", "td_nod": "C&C Tiberian Dawn",
    "ts_gdi": "C&C Tiberian Sun", "ts_nod": "C&C Tiberian Sun",
    "cabal": "C&C Tiberian Sun", "forgotten": "C&C Tiberian Sun",
    "ra1_allies": "Red Alert", "ra1_soviets": "Red Alert", "modjapan": "Red Alert (Japan)",
    "ra2_allies": "Red Alert 2", "ra2_soviets": "Red Alert 2", "yuri": "Red Alert 2",
    "asianalliance": "Cameo original", "steelconsortium": "Cameo original",
    "latinsyndicate": "Cameo original", "naxis": "Cameo original",
    "schwarzermond": "Cameo original", "futuretech": "Cameo original",
    "tkm": "Cameo original (TKM)",
    "atreides": "Dune 2000", "harkonnen": "Dune 2000",
    "ordos": "Dune 2000", "ixian": "Dune 2000",
    "terran": "StarCraft", "zerg": "StarCraft", "protoss": "StarCraft",
    "wc2_humans": "WarCraft 2", "wc2_orcs": "WarCraft 2",
    "plymouth": "Outpost 2", "eden": "Outpost 2",
}


def main() -> int:
    m = Model()
    rs = m.rs
    random_pool = m.random_pool()
    tourney_pool = m.tournament_pool()

    # ai.yaml referenced ids (build lists only)
    ai_ids: set[str] = set()
    ai_doc = load_yaml(m.root / "mods/cameo/ai/ai.yaml")

    def walk(n):
        yield n
        for c in n.children:
            yield from walk(c)

    for top in ai_doc:
        for node in walk(top):
            if node.key in ("UnitsToBuild", "BuildingFractions",
                            "UnitLimits", "BuildingLimits"):
                ai_ids.update(e.key.strip().lower() for e in node.children)

    print("# Faction Matrix")
    print()
    print("_Generated by `tools/audit/gen_faction_matrix.py` — do not edit by "
          "hand; regenerate after roster changes (CI should enforce no drift)._")
    print()
    print("**Measurement notes:** roster counts come from the prerequisite-"
          "closure buildable set (see `tools/audit/cameo_model.py`); "
          "`AI` = share of the faction's combat units referenced anywhere in "
          "ai.yaml build lists; `Fluent` = share of buildable tooltips using "
          "Fluent keys rather than literals.")
    print()

    rows = []
    for fac in sorted(m.factions.values(), key=lambda f: (f.is_meta, f.internal.lower())):
        if fac.is_meta:
            rows.append([fac.internal, fac.name, fac.side, "—",
                         "meta", "—", "—", "—", "—", "—",
                         f"{len(fac.random_members)} members"])
            continue
        roster = m.buildable_roster(fac.internal)
        types = Counter(m.unit_type(a) for a in roster)
        combat = [a for a in roster
                  if m.unit_type(a) in {"inf", "veh", "air", "nav"}
                  and (rs.resolve(a) and rs.resolve(a).child("Health") is not None)]
        wired = sum(1 for a in combat if a in ai_ids)
        fluent_total = fluent_ok = 0
        files = Counter()
        for a in roster:
            res = rs.resolve(a)
            if res is None:
                continue
            src = str(rs.actor(a).file).replace("\\", "/")
            files[src.split("mods/cameo/")[-1]] += 1
            tt = res.get("Tooltip", "Name")
            if tt:
                fluent_total += 1
                if looks_like_fluent(tt):
                    fluent_ok += 1
        # ⚠ Break the tie by NAME. `Counter.most_common` falls back to insertion order, which
        # comes from an unordered walk, so a faction whose files tie on count (ts_nod: vehicles
        # and buildings, 23 each) named a different file on every run — churn in TRACKED evidence
        # (CLAUDE.md rule 8). Third instance of this class in one regeneration; see also
        # audit_buildable_order and audit_packs.
        main_file = min(files.items(), key=lambda kv: (-kv[1], kv[0]))[0] if files else "—"
        ai_status = ("yes" if combat and wired == len(combat)
                     else f"partial {wired}/{len(combat)}" if wired else "NO")
        rows.append([
            fac.internal, fac.name, fac.side,
            GAME_OF_SIDE_HINTS.get(fac.internal, "?"),
            "yes" if fac.selectable else "no",
            "yes" if fac.internal in random_pool else "no",
            "yes" if fac.internal in tourney_pool else "no",
            main_file,
            f"{sum(types[t] for t in ('inf','veh','air','nav'))}u/"
            f"{types['bld']+types['def']}b/{types['upg']}up",
            ai_status,
            f"{(100*fluent_ok//fluent_total) if fluent_total else 0}%",
        ])

    print(table(["internal", "display name", "side", "source game", "selectable",
                 "Random", "Tournament", "main rules file",
                 "units/bldgs/upgrades", "AI wired", "Fluent"], rows))
    return 0


if __name__ == "__main__":
    sys.exit(main())
