#!/usr/bin/env python3
"""peer_cost_grid.py — what shipped OpenRA mods actually charge, and at what resolution.

    python tools/reference/peer_cost_grid.py

Two numbers the band law in `BALANCE_PIPELINE` §8.1a rests on, measured rather than assumed:

  1. **COST ELASTICITY** — regress `log(cost)` on `log(HP)` and `log(DPS)` over the armed
     mobile units of every peer mod. `a + b` says what doubling BOTH stats costs in a game
     people actually play, which is the only external check on Cameo's own formula.
  2. **COST RESOLUTION** — the median ratio between adjacent distinct costs. Two units
     priced closer together than that are not distinguishable to a player, so it is the
     natural width of a "rung" and therefore how many units a band of a given width holds.

⛔ POOL WITH MOD FIXED EFFECTS OR THE ANSWER IS GARBAGE. Each mod sets its own power level
and its own HP scale (WC2 hundreds, C&C hundreds of thousands), so a naive pooled
regression across mods reads a+b = 0.10 at R^2 = 0.08 — a confident number that means
nothing, because the between-mod scale differences swamp the within-mod signal. Demeaning
each log WITHIN its mod first gives a+b = 0.84 at R^2 = 0.43, which agrees with the median
of the 14 separate per-mod fits. The two agreeing is the check that the pooling is sound.

Source: `docs/design/ORIGINAL_UNITS_PEER_OPENRA.md`, itself generated by
`extract_peer_units.py` from each mod's own checkout through `miniyaml.Ruleset`.
"""
from __future__ import annotations
import collections, math, pathlib, re, statistics

ROOT = pathlib.Path(__file__).resolve().parents[2]
DOC = ROOT / "docs/design/ORIGINAL_UNITS_PEER_OPENRA.md"
MIN_UNITS = 12   # below this a per-mod fit is noise


def parse():
    """Rows out of the generated peer table. Columns are fixed by extract_peer_units.py."""
    rows, mod = [], None
    for line in DOC.read_text(encoding="utf-8").splitlines():
        m = re.match(r"^## (.+?)\s*(\(\d+ buildable units\))?$", line)
        if m:
            mod = m.group(1).strip()
            continue
        if not line.startswith("| `"):
            continue
        c = [x.strip() for x in line.strip().strip("|").split("|")]
        if len(c) < 16:
            continue

        def num(s):
            try:
                return float(s.replace(",", "").replace("x", ""))
            except ValueError:
                return None
        rows.append(dict(mod=mod, id=c[0].strip("`"), type=c[2], hp=num(c[3]),
                         cost=num(c[5]), limit=c[10], dps=num(c[15])))
    return rows


def ols2(ys, x1s, x2s):
    """log-log OLS on two regressors. No numpy in this tree."""
    n = len(ys)
    m1, m2, my = sum(x1s) / n, sum(x2s) / n, sum(ys) / n
    a1 = [v - m1 for v in x1s]; a2 = [v - m2 for v in x2s]; ay = [v - my for v in ys]
    s11 = sum(v * v for v in a1); s22 = sum(v * v for v in a2)
    s12 = sum(a1[i] * a2[i] for i in range(n))
    s1y = sum(a1[i] * ay[i] for i in range(n)); s2y = sum(a2[i] * ay[i] for i in range(n))
    det = s11 * s22 - s12 * s12
    if abs(det) < 1e-12:
        return None
    b1 = (s22 * s1y - s12 * s2y) / det
    b2 = (s11 * s2y - s12 * s1y) / det
    ssr = sum((ay[i] - b1 * a1[i] - b2 * a2[i]) ** 2 for i in range(n))
    sst = sum(v * v for v in ay)
    return b1, b2, (1 - ssr / sst if sst else 0.0), n


def main() -> int:
    rows = parse()
    combat = [r for r in rows
              if r["type"] in ("vehicle", "infantry", "aircraft")
              and all((r["hp"], r["cost"], r["dps"]))
              and r["hp"] > 0 and r["cost"] > 0 and r["dps"] > 0
              # build-limited heroes and superweapons are priced on influence, not stats
              and r["limit"] in ("—", "-", "")]
    by = collections.defaultdict(list)
    for r in combat:
        by[r["mod"]].append(r)
    mods = {m: s for m, s in by.items() if len(s) >= MIN_UNITS}

    print("# Peer cost grid — 14 shipped OpenRA mods\n")
    print("## 1. Cost elasticity  `cost ~ HP^a · DPS^b`\n")
    print("| mod | n | a (HP) | b (DPS) | **a+b** | R² | doubling BOTH stats costs |")
    print("|---|--:|--:|--:|--:|--:|--:|")
    per = []
    for m in sorted(mods):
        s = mods[m]
        res = ols2([math.log(r["cost"]) for r in s], [math.log(r["hp"]) for r in s],
                   [math.log(r["dps"]) for r in s])
        if not res:
            continue
        a, b, r2, n = res
        per.append(a + b)
        print(f"| {m} | {n} | {a:.2f} | {b:.2f} | **{a+b:.2f}** | {r2:.2f} | {2**(a+b):.2f}x |")

    ys, x1, x2 = [], [], []
    for s in mods.values():
        lc = [math.log(r["cost"]) for r in s]
        lh = [math.log(r["hp"]) for r in s]
        ld = [math.log(r["dps"]) for r in s]
        mc, mh, md = sum(lc)/len(lc), sum(lh)/len(lh), sum(ld)/len(ld)
        ys += [v - mc for v in lc]; x1 += [v - mh for v in lh]; x2 += [v - md for v in ld]
    a, b, r2, n = ols2(ys, x1, x2)
    print(f"| **POOLED, mod fixed effects** | **{n}** | **{a:.2f}** | **{b:.2f}** | "
          f"**{a+b:.2f}** | {r2:.2f} | **{2**(a+b):.2f}x** |")
    print(f"\nper-mod `a+b`: median **{statistics.median(per):.2f}**, "
          f"range {min(per):.2f}–{max(per):.2f} over {len(per)} mods. The pooled fit and the "
          f"median of the separate fits agree, which is the check that the pooling is sound.\n")
    print("⭐ Cameo's class formula runs a combined elasticity of **1.16** over ×0.5…×2 "
          "(`tools/tests/test_band_law.py`) — steeper than 12 of these 14.\n")

    print("## 2. Cost resolution — the median step between adjacent distinct costs\n")
    print("| mod | armed mobile units | distinct costs | median step | units per cost | "
          "distinct costs per unit |")
    print("|---|--:|--:|--:|--:|--:|")
    steps = []
    for m in sorted(mods):
        s = mods[m]
        cs = sorted({r["cost"] for r in s})
        st = [cs[i+1]/cs[i] for i in range(len(cs)-1) if cs[i] > 0]
        steps += st
        print(f"| {m} | {len(s)} | {len(cs)} | {statistics.median(st):.3f}x | "
              f"{len(s)/len(cs):.2f} | {len(cs)/len(s):.3f} |")
    med = statistics.median(steps)
    print(f"\n**median adjacent step over all {len(steps)} gaps: {med:.3f}x** — "
          f"the value `band_granularity.PEER_STEP` carries.\n")
    for w, label in ((2.50/(35/48), "target band 0.729–2.50"), (4.00/0.50, "hard band 0.50–4.00")):
        print(f"- {label}: width {w:.2f}x -> **{math.log(w)/math.log(med):.1f} distinct rungs**")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
