"""Generate and verify an INACTIVE, standalone MiniYAML two-stage Hydra pilot.

No active manifest, actor, weapon, ledger or reviewed exception is edited.
The pilot has one preserved chemical main and a fitted nonchemical SpreadDamage.
The grid is a flat-payload diagnostic; seven actor cases reuse the ordered lab.
"""
from __future__ import annotations

import argparse
import json
import pathlib
from fractions import Fraction

from hydra_impact_lab import (
    ROOT, Ruleset, Node, TARGETS, enabled, impact, modifiers, replace,
    target_from_actor, falloff_and_radii, runtime_falloff)
from hydra_impact_lab import require_legacy_hydra
from miniyaml import load
import percentage_damage as pd

PILOT = ROOT/'tools/balance/pilots/hydra_two_stage.yaml'
REPORT = ROOT/'docs/design/HYDRALISK_TWO_STAGE_PILOT.md'
DATA = ROOT/'docs/audit/latest/hydralisk_two_stage_pilot.json'
NAME = 'HydraSpitTwoStagePilot'
NONCHEMICAL = ('Warhead@LightMissile', 'Warhead@SmallArms', 'Warhead@ArrowWeapon')
MASKS = ((), ('BulletImmune',), ('wall',), ('BulletImmune','wall'))


def fingerprint(node):
    return (node.key,node.value,tuple(fingerprint(n) for n in node.children))


def damage(nodes, armor, distance, flags=()):
    """Flat positional damage before outgoing/defense/state modifiers.

    All selected targets are assumed to match Ground/Water/Air. Only the two
    nonchemical exclusion tags vary here. No multi-armor/plating simulation.
    """
    total=0
    for node in nodes:
        invalid=set((node.get('InvalidTargets') or '').replace(' ','').split(','))
        if invalid.intersection(flags):
            continue
        fo,radii,_=falloff_and_radii(node)
        total+=modifiers(int(node.get('Damage')), (pd.versus_table(node).get(armor,100),
                                                 runtime_falloff(fo,radii,distance)))
    return total


def fit(current):
    require_legacy_hydra(current)
    nodes=[current.child(k) for k in NONCHEMICAL]
    armors=sorted(set().union(*(pd.versus_table(n) for n in nodes)))
    knots=sorted(set().union(*(falloff_and_radii(n)[1] for n in nodes)))
    # Continuous midpoint minimizes error normalized by each armor's center
    # damage at this knot. Rounding it does NOT prove the optimal integer-runtime
    # fit, global optimality over all distances, or acceptable gameplay drift.
    curve=[]
    for distance in knots:
        required=[Fraction(damage(nodes,a,distance),damage(nodes,a,0)) for a in armors]
        curve.append(round(100*(min(required)+max(required))/2))
    pilot=current.deep_copy()
    pilot.key=NAME
    pilot.children=[n for n in pilot.children if n.key not in NONCHEMICAL[1:]]
    merged=pilot.child(NONCHEMICAL[0])
    total=sum(int(n.get('Damage')) for n in nodes)
    replace(merged,'Damage',total)
    for armor in armors:
        numerator=sum(int(n.get('Damage'))*pd.versus_table(n).get(armor,100) for n in nodes)
        if numerator % total:
            raise ValueError(f'Cannot exactly encode center Versus row for {armor}')
        replace(merged.child('Versus'),armor,numerator//total)
    replace(merged,'Range',', '.join(map(str,knots)))
    replace(merged,'Falloff',', '.join(map(str,curve)))
    return pilot,armors,knots,curve


def yaml_text(node):
    lines=['# INACTIVE EXPERIMENT: not included by mods/cameo/mod.yaml.',
           '# Generated by tools/balance/hydra_two_stage_pilot.py --write.',
           '# Standalone definition, NOT a merge overlay onto HydraSpit.',
           '# Do not activate: target-exclusion, geometry and damage-type deltas remain.']
    def emit(n,depth):
        lines.append('\t'*depth+n.key+':'+(' '+n.value if n.value else ''))
        for child in n.children:
            emit(child,depth+1)
    emit(node,0)
    return '\n'.join(lines)+'\n'


def compare(current,pilot,armors):
    originals=[current.child(k) for k in NONCHEMICAL]
    merged=[pilot.child(NONCHEMICAL[0])]
    rows=[]
    for flags in MASKS:
        worst_absolute=None
        worst_normalized=None
        changed=0
        new_damage_cases=0
        samples=0
        for armor in armors:
            reference=damage(originals,armor,0,flags)
            for distance in range(801):
                before=damage(originals,armor,distance,flags)
                after=damage(merged,armor,distance,flags)
                delta=after-before
                row=dict(armor=armor,distance=distance,before=before,after=after,delta=delta,
                         relative_change=(delta/before if before else None),
                         center_normalized_error=abs(delta)/reference)
                changed+=bool(delta)
                new_damage_cases+=before==0 and after>0
                samples+=1
                if worst_absolute is None or abs(delta)>abs(worst_absolute['delta']):
                    worst_absolute=row
                if worst_normalized is None or row['center_normalized_error']>worst_normalized['center_normalized_error']:
                    worst_normalized=row
        rows.append(dict(flags=list(flags),cases=samples,changed_cases=changed,
                         newly_damaged_cases=new_damage_cases,worst_absolute=worst_absolute,
                         worst_center_normalized=worst_normalized))
    return rows


def evidence(rules,current,pilot,armors,knots,curve,*,targets=None,firepower=None):
    if (targets is None) != (firepower is None):
        raise ValueError('Explicit historical evidence requires targets and firepower together')
    if targets is None:
        shooter=rules.resolve('zerg_hydralisk')
        firepower=[int(n.get('Modifier')) for n in shooter.children_named('FirepowerMultiplier') if enabled(n)]
        targets=[target_from_actor(rules.resolve(name)) for name in TARGETS]
    fp=firepower
    actors=[]
    for target in targets:
        name=target.name
        samples=[]
        for d in (0,55,110,220,350,420,700,800):
            before=impact(current,target,fp,d)
            after=impact(pilot,target,fp,d)
            samples.append(dict(distance=d,before=before['total'],after=after['total'],
                                delta=after['total']-before['total'],
                                corrosion_before=before['corrosion'],corrosion_after=after['corrosion']))
        actors.append(dict(name=name,samples=samples))
    protected=[n for n in current.children if n.key not in NONCHEMICAL]
    unchanged=all(fingerprint(n)==fingerprint(pilot.child(n.key)) for n in protected)
    originals=[current.child(k) for k in NONCHEMICAL]
    # Non-separability witness: a single Versus table x one curve cannot retain
    # different normalized radial responses for two armor types simultaneously.
    witness={a:[damage(originals,a,d) for d in (0,350)] for a in ('None','Heavy')}
    return dict(schema=1,activation='blocked: preservation checks fail',
                scope='inactive standalone MiniYAML pilot; no gameplay changes',
                protected_nodes_unchanged=unchanged,armors=armors,range=knots,falloff=curve,
                comparison=compare(current,pilot,armors),nonseparability_witness=witness,
                changed_damage_types={n.key:n.get('DamageTypes') for n in originals},
                actor_samples=actors)


def report(data):
    lines=['# Two-stage Hydralisk implementation pilot','',
        '**Implemented as an inactive standalone MiniYAML weapon; not safe to activate.**',
        'The live Hydra, all stats, manifests, ledgers and reviewed exception remain unchanged.','',
        '## Implementation','',
        '- Preserve the resolved chemical main, all four percentage hits and their order.',
        '- Keep the original missile flat-hit slot, increase it to 54000 and replace its',
        '  armor table with the exact damage-weighted center table of the three nonchemical hits.',
        '- Remove only the SmallArms and Arrow flat nodes. Preserve firing/projectile/effect fields.',
        '- Fit one piecewise falloff using a rounded continuous minimax midpoint at each',
        '  original radius knot. Integer damage rounding and between-knot behavior mean',
        '  this is not a claim of optimality for the complete runtime grid.','',
        'Range: `'+', '.join(map(str,data['range']))+'`',
        'Falloff: `'+', '.join(map(str,data['falloff']))+'`','',
        '## Flat-payload preservation checks','',
        'Every integer distance 0–800 is checked for every authored class armor row.',
        'Only the three nonchemical flat hits are compared here, before actor modifiers.',
        'Tag combinations are synthetic routing probes, not claims that every actor/armor',
        'combination exists in the live roster.',
        'Ordinary targets and the two exclusion tags are kept separate. No tolerance is',
        'silently treated as approval; changed cases remain failures of exact preservation.','',
        '| Target flags | Cases | Changed | Worst absolute delta | Worst error / original center damage |',
        '|---|---:|---:|---:|---:|']
    for row in data['comparison']:
        lines.append('| '+(', '.join(row['flags']) or 'ordinary')+f" | {row['cases']} | {row['changed_cases']} | {row['worst_absolute']['delta']:+} | {row['worst_center_normalized']['center_normalized_error']:.1%} |")
    witness=data['nonseparability_witness']
    lines+=['','## Why one flat hit cannot preserve the old behavior','',
        'The old nonchemical payload has three different target masks: missile excludes neither',
        'tag, SmallArms excludes BulletImmune, and Arrow excludes wall. The pilot inherits the',
        'broad missile mask. That restores excluded damage; using the union instead would remove',
        'legitimate damage from other components. One common mask cannot represent both cases.','',
        f"At distance 350, None retains {witness['None'][1]}/{witness['None'][0]} of its center damage;",
        f"Heavy retains {witness['Heavy'][1]}/{witness['Heavy'][0]}. These ratios differ.",
        'A single armor table multiplied by a common falloff cannot reproduce both radial responses.',
        'Per-hit rounding adds further differences; it does not explain away this mismatch.','',
        'The merged hit also uses the missile damage types. That does not preserve the separate',
        'BulletDeath contributions. Friendly-fire/target-discovery behavior is not modeled by',
        'the numeric grid and has not been declared equivalent.','',
        '## Ordered actor projections','',
        'The seven-actor lab holds targets alive and models one enemy impact, including TakeCover',
        'and Corrosion feedback. Values are potential damage, not HP lost or playtest results.','',
        '| Actor | Center before → after | Distance 110 before → after | Distance 350 before → after |',
        '|---|---|---|---|']
    for row in data['actor_samples']:
        selected={s['distance']:s for s in row['samples']}
        cells=[f"{selected[d]['before']} → {selected[d]['after']}" for d in (0,110,350)]
        lines.append('| '+row['name']+' | '+' | '.join(cells)+' |')
    lines+=['','## Disposition','',
        'Do not activate this pilot. The two-stage approach preserves the chemical sequence',
        'and improves center behavior, but fitting the splash curve does not solve the target-mask',
        'or armor-distance incompatibility. Exact preservation requires retaining the separate',
        'nonchemical applications, or a new composite runtime implementation. The latter is',
        'disproportionate for this one weapon and is not part of this task.','',
        'Current Hydra stays on four profiles. A deliberate redesign remains possible, but its',
        'changed immunity, splash and death-type behavior is a gameplay choice, not a cleanup.','',
        'Reproduce with `tools/run-bounded-python.ps1 -PythonArguments @(\'tools/balance/hydra_two_stage_pilot.py\', \'--check\')`.',
        'The pilot is in `tools/balance/pilots/hydra_two_stage.yaml`, outside all active includes.',
        'No game launch is required for these static checks.','']
    return '\n'.join(lines)


def main():
    parser=argparse.ArgumentParser()
    mode=parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write',action='store_true')
    mode.add_argument('--check',action='store_true')
    args=parser.parse_args()
    rules=Ruleset(ROOT)
    current=rules.resolve_weapon('HydraSpit')
    try:
        pilot,armors,knots,curve=fit(current)
    except ValueError as error:
        raise SystemExit(str(error))
    data=evidence(rules,current,pilot,armors,knots,curve)
    outputs={PILOT:yaml_text(pilot),REPORT:report(data),DATA:json.dumps(data,indent=2)+'\n'}
    if args.write:
        PILOT.parent.mkdir(parents=True,exist_ok=True)
        for path,text in outputs.items():
            path.write_text(text,encoding='utf-8')
    else:
        for path,text in outputs.items():
            if path.read_text(encoding='utf-8')!=text:
                raise SystemExit(f'STALE: {path.relative_to(ROOT)}')
    parsed=load(PILOT)
    if len(parsed)!=1 or fingerprint(parsed[0])!=fingerprint(pilot):
        raise SystemExit('Pilot MiniYAML round-trip differs')
    print('PASS: pilot artifacts are fresh and MiniYAML round-trip matches.')
    print('BLOCKED FOR ACTIVATION: target masks, radial armor response and damage types differ.')


if __name__=='__main__':
    main()
