#!/usr/bin/env python3
"""propose_rebalance.py — pipeline-driven rebalance proposal for one faction.

Produces docs/balance/rebalance_<faction>.md: per-unit raw stats, the
formula price vs the actual cost, outlier flags, and (when present)
promotion-replacement superiority checks (DESIGN §15). ANALYSIS ONLY —
changes go through the normal ledger -> apply loop after maintainer
approval, per the balance law.

Usage: python tools/balance/propose_rebalance.py --faction redalert2mod_schwarzermond
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools/balance"))
import formula  # noqa: E402

LEDGER = ROOT / "docs/balance"

COMBAT_SECTIONS = ("infantry", "vehicles", "aircraft", "naval", "defenses")


def fnum(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def unit_row(u):
    hp = fnum((u.get("hp") or {}).get("v"))
    speed = fnum((u.get("speed") or {}).get("v") or (u.get("speed_air") or {}).get("v"))
    cost = fnum((u.get("cost") or {}).get("v"))
    d = u.get("design") or {}
    fp_pct = fnum((u.get("firepower_multiplier") or {}).get("v"))
    fp = (fp_pct / 100.0) if fp_pct is not None else 1.0
    total_dps, best_range = 0.0, 0.0
    arms = [a for a in u.get("armaments", []) if a.get("pricing", True)]
    # Use the primary armament for pricing; fall back to the first pricing armament.
    primary = next((a for a in arms if a.get("slot") == "Armament@PRIMARY"), arms[0] if arms else None)
    if primary is not None:
        reload_ = fnum(primary.get("reloaddelay"))
        burst = int(fnum(primary.get("burst")) or 1)
        best_range = formula.wdist_value(primary.get("range"), 0.0)
        if reload_:
            # Sum the main damage warheads; ignore chip ExtraDamage and Percentage warheads.
            damage = 0.0
            for w in primary.get("warheads", []):
                if w.get("type") != "SpreadDamage":
                    continue
                tag = w.get("tag", "")
                if tag.endswith("ExtraDamage") or tag.endswith("Percentage"):
                    continue
                dmg = fnum(w.get("damage"))
                if dmg is not None:
                    damage += dmg
            if damage:
                total_dps = formula.dps(damage, reload_, burst,
                                        primary.get("burstdelays"),
                                        firepower_multiplier=fp)
    return hp, speed, best_range, total_dps, cost, d


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--faction", required=True, help="ledger name")
    ap.add_argument("--defense-speed", type=float, default=100.0)
    args = ap.parse_args()

    doc = json.loads((LEDGER / f"{args.faction}.json").read_text(encoding="utf-8"))
    lines = [f"# Rebalance proposal — {args.faction}",
             "",
             "_Generated by propose_rebalance.py from the balance ledger. "
             "ANALYSIS ONLY — nothing applied. Prices use the Tiger global "
             "formula with the seeded design judgments (units without seeds "
             "price with modifiers of 1 — treat those rows as provisional). "
             "Maintainer approves per row, then the change runs through the "
             "pipeline (ledger edit -> apply_balance --confirm)._",
             ""]
    outliers, unseeded = [], 0
    for section in COMBAT_SECTIONS:
        sec = doc["sections"].get(section)
        if not sec:
            continue
        lines += [f"## {section}", "",
                  "| unit | HP | Spd | Rng(wd) | DPS | UC | K | Tier | "
                  "formula price | cost | Δ% | flag |",
                  "|---|---|---|---|---|---|---|---|---|---|---|---|"]
        for actor, u in sorted(sec.items()):
            hp, speed, rng, dps_v, cost, d = unit_row(u)
            if speed is None and section == "defenses":
                speed = args.defense_speed
            if hp is None or cost is None:
                continue
            uc = fnum(d.get("unit_class"))
            k = fnum(d.get("special"))
            tier = fnum(d.get("tech_tier"))
            seeded = any(x is not None for x in (uc, k, tier))
            if not seeded:
                unseeded += 1
            if dps_v and speed is not None:
                price = formula.price(hp, speed, rng, dps_v,
                                      k or 1.0, uc or 1.0, tier or 1.0)
                delta = (price - cost) / cost if cost else 0.0
                flag = ""
                if abs(delta) >= 0.6:
                    flag = "❗"
                    outliers.append((actor, section, cost, price, delta, seeded))
                elif abs(delta) >= 0.25:
                    flag = "⚠"
                lines.append(
                    f"| `{actor}` | {hp:.0f} | {speed:.0f} | {rng:.0f} | "
                    f"{dps_v:.0f} | {uc if uc is not None else '·'} | "
                    f"{k if k is not None else '·'} | "
                    f"{tier if tier is not None else '·'} | "
                    f"{price:.0f} | {cost:.0f} | {delta:+.0%} | {flag}"
                    f"{'' if seeded else ' (unseeded)'} |")
            else:
                lines.append(f"| `{actor}` | {hp:.0f} | "
                             f"{speed if speed is not None else '·'} | · | "
                             f"(no weapon) | · | · | · | — | {cost:.0f} | | |")
        lines.append("")

    lines += ["## Worst outliers (|Δ| ≥ 60%) — investigate stats before touching price", ""]
    for actor, section, cost, price, delta, seeded in \
            sorted(outliers, key=lambda x: -abs(x[4]))[:25]:
        note = "" if seeded else " — UNSEEDED (judgments default to 1; seed first)"
        lines.append(f"- `{actor}` ({section}): cost {cost:.0f} vs formula "
                     f"{price:.0f} ({delta:+.0%}){note}")
    lines += ["", f"_unseeded combat units in this faction: {unseeded} — "
              "their formula prices assume UC=K=Tier=1 and are NOT actionable "
              "until seeded (fit_class.py / manual design entry)._"]

    out = LEDGER / f"rebalance_{args.faction}.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {out.relative_to(ROOT)} ({len(outliers)} outliers flagged)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
